spring.application.name=homies

spring.datasource.url=jdbc:postgresql://localhost:5432/homies
spring.datasource.username=postgres
spring.datasource.password=3694
spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet=DEBUG

recaptcha.site.key=6Le4eKcqAAAAAMdOHKCDSy3U6cyRF4m1Mgxsglya
recaptcha.secret.key=6Le4eKcqAAAAAM9SLfkzztxNO8TZUT3vEqhViOHt